(***********************************************************************)
(*                                                                     *)
(*                          HEVEA                                      *)
(*                                                                     *)
(*  Luc Maranget, projet Moscova, INRIA Rocquencourt                   *)
(*                                                                     *)
(*  Copyright 2001 Institut National de Recherche en Informatique et   *)
(*  Automatique.  Distributed only by permission.                      *)
(*                                                                     *)
(*  $Id: explode.mli,v 1.2 2001-05-25 09:20:44 maranget Exp $"            *)
(***********************************************************************)
val trees : Tree.style Tree.t list -> Htmltext.style Tree.t list
