#! /bin/sh

case $1 in
  '')
   BASE=image
   ;;
  *)
   BASE=$1
  ;;
esac

NAME=${BASE}.image

test -r  ${NAME}.tex || exit 2
latex < /dev/null ${BASE}.image.tex 
dvips -t a3 -x1414 -S 1 -i -o${BASE} ${NAME}.dvi
/bin/rm -f ${NAME}.log ${NAME}.aux ${NAME}.dvi

test -f pat[0-9][0-9][0-9] && \
for i in ${BASE}[0-9][0-9][0-9]
do
  mv $i $i.ps
  (echo "($i.ps) run" ; echo "quit") |\
  gs -q -sPAPERSIZE=a3 -dNOPAUSE -dNO_PAUSE -sDEVICE=ppmraw -sOutputFile=$i.ppm
  pnmcrop < $i.ppm | ppmtogif | giftrans -t '#ffffff' > $i.gif
  /bin/rm -f $i.ps $i.ppm
done